# Generated by Django 5.0 on 2023-12-12 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField()),
                ('monthly_amount', models.FloatField(default=80000)),
                ('installment_amount', models.FloatField(default=0)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member', verbose_name='نام عضو')),
            ],
        ),
    ]
