# Generated by Django 5.0 on 2023-12-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='MonthlyReceipt',
        ),
    ]
