# Generated by Django 5.0 on 2023-12-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=250)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('member_capital', models.FloatField()),
                ('member_dept', models.FloatField()),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.family', verbose_name='خانواده')),
            ],
        ),
    ]
